//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimeTrackerDbEntities : DbContext
    {
        public TimeTrackerDbEntities()
            : base("name=TimeTrackerDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            Database.SetInitializer<TimeTrackerDbEntities>(new CreateDatabaseIfNotExists<TimeTrackerDbEntities>());

            modelBuilder.Entity<Task>().ToTable("Tasks", "TimeTrackerDb");
            modelBuilder.Entity<TasksStatu>().ToTable("TasksStatus", "TimeTrackerDb");
            modelBuilder.Entity<User>().ToTable("Users", "TimeTrackerDb");
            modelBuilder.Entity<UsersTask>().ToTable("UsersTasks", "TimeTrackerDb");
            modelBuilder.Entity<WorkingCard>().ToTable("WorkingCard", "TimeTrackerDb");

        }
    
        public DbSet<Task> Tasks { get; set; }
        public DbSet<TasksStatu> TasksStatus { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UsersTask> UsersTasks { get; set; }
        public DbSet<WorkingCard> WorkingCard { get; set; }
    }
}
