//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersTask
    {
        public int UserID { get; set; }
        public int TaskId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<double> WorkedHours { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
    }
}
